# industree colors for foot
# Upstream: https://github.com/swield/industree/raw/main/extras/foot/industree.ini

[cursor]
color=0e1b21 00ffd7

[colors]
foreground=c8e7f7
background=0e1b21
selection-foreground=c8e7f7
selection-background=004968

regular0=1b292f
regular1=9e001b
regular2=07b57b
regular3=b38d03
regular4=006bb4
regular5=9e3699
regular6=07b699
regular7=89a7b6

bright0=4b6775
bright1=ff223a
bright2=00ffaf
bright3=ffca00
bright4=49a9ff
bright5=da6fd3
bright6=00ffd7
bright7=c8e7f7
