# vim:ft=kitty

## name: industree
## license: MIT
## author: swield
## upstream: https://github.com/swield/industree/raw/main/extras/kitty/industree.conf

background #0e1b21
foreground #c8e7f7
cursor #00ffd7
cursor_text_color #0e1b21
selection_background #004968
selection_foreground #c8e7f7

# tabs
active_tab_foreground #00ffd7
active_tab_background #18252c
active_tab_font_style bold
inactive_tab_foreground #7a98a7
inactive_tab_background #132026
tab_bar_background #132026

# normal
color0 #1b292f
color1 #9e001b
color2 #07b57b
color3 #b38d03
color4 #006bb4
color5 #9e3699
color6 #07b699
color7 #89a7b6

# bright
color8 #4b6775
color9 #ff223a
color10 #00ffaf
color11 #ffca00
color12 #49a9ff
color13 #da6fd3
color14 #00ffd7
color15 #c8e7f7
